version: '3'
services:
  nginx:
    build: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./acme/certs:/etc/letsencrypt
      - ./nginx/data:/var/www
    depends_on:
      - thelounge
      - yanius
    links:
      - php
  php:
    build: php
    volumes:
      - ./nginx/data:/var/www
  thelounge:
    image: thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "127.0.0.1:9000:9000"
    restart: always
    volumes:
      - ./thelounge:/var/opt/thelounge
  rethinkdb:
    image: rethinkdb
    container_name: rethinkdb
    ports:
      - "127.0.0.1:28015:28015"
    volumes:
      - ./rethinkdb:/data
  yanius:
    build: yanius
    container_name: yanius
    ports:
      - "56792:56792"
    depends_on:
      - rethinkdb
    tty: true
  znc:
    image: znc
    volumes:
      - ./znc:/znc-data
    ports:
      - "127.0.0.1:5000:5000"
